# Site settings
title: I'm Azmain Adel
description: ""
# baseurl: "/home" 
# url: "" 

# User settings
username: Azmain Adel
<<<<<<< HEAD
# user_description: 
# user_title: Software Developer
email: azmainadel47@gmail.com
twitter_username: 
github_username:  azmainadel
gplus_username: 

# Others
greeting: Hey, I'm
=======
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
>>>>>>> e37158d7389e961b7a2567066f824d9c30fa2481

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
