# Site settings
title: I'm Azmain Adel
description: ""
# baseurl: "/home" 
# url: "" 

# User settings
username: Azmain Adel
# user_description: 
# user_title: Software Developer
email: azmainadel47@gmail.com
twitter_username: 
github_username:  azmainadel
gplus_username: 

# Others
greeting: Hey, I'm

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
